### PR TITLE
Add multi-stage Dockerfile to Kraken

### PR DESCRIPTION
**Pull request by mej**
* Add new `Dockerfile` that uses multi-stage build features and techniques to support building multiple Alpine-based Kraken
  containers of various persuasions, from a full Go dev/build environment all the way down to just the `/sbin/kraken` executable
  itself.

* Also add a `.dockerignore` file (analogous to `.gitignore`) to prevent Git and CircleCI metadata trees from being inadvertantly
  included in the containers/repositories.

* Add default `config.yaml` and `state.json` config files to the `.gitignore` list to help facilitate building containers #4 and #5
  (those which are pre-populated with the aforementioned files from the top-level directory) without having them appear untracked.

* Add script-generated "kitchen sink" config file to `.gitignore` for much the same reason (and to avoid accidentally committing it).

### CODE REVIEW

**Comment by mej** [comment]
**_Note:_**  The simplest and most straight-forward way to build and tag all the repositories correctly is to copy-and-paste this command and run it from the top-level `kraken` tree:

``` bash
(for STAGE in "-t kraken-dev-go${GOVER:-1.15}-alpine:latest --target kraken-build" "-t kraken-alpine:latest --target kraken-alpine" "-t kraken-exe --target kraken-exe" ; do docker build --pull ${STAGE} . ; done ; if [[ -s config.yaml && -s state.json ]]; then for STAGE in "-t kraken-dev-go${GOVER:-1.15}-alpine-cfg:latest --target kraken-build-cfg" "-t kraken-alpine-cfg:latest --target kraken-alpine-cfg" ; do docker build --pull ${STAGE} . ; done ; fi)
```

Here's the same shell command minus the subshell and broken out for readability:

``` bash
for STAGE in "-t kraken-dev-go${GOVER:-1.15}-alpine:latest --target kraken-build"
             "-t kraken-alpine:latest --target kraken-alpine"
             "-t kraken-exe --target kraken-exe"
 do
    docker build --pull ${STAGE} .
done
if [[ -s config.yaml && -s state.json ]]; then
    for STAGE in "-t kraken-dev-go${GOVER:-1.15}-alpine-cfg:latest --target kraken-build-cfg"
                 "-t kraken-alpine-cfg:latest --target kraken-alpine-cfg"
    do
         docker build --pull ${STAGE} .
    done
fi
```

**Comment by jlowellwofford** [comment]
@mej Can you address the linting issues?

**Comment by mej** [comment]
Linting comes back clean now (*grumble*), so you should be good to merge at your discretion. 🙄 😆

**Comment by jlowellwofford** [comment]
This gives a good basis to iterate on.  Merging.  Note: the location of the Dockerfile will probably change in the future, but this is fine for now.

**Pull request merged**
